koalamon_integration_core:
    resource: "@KoalamonIntegrationWebhookBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_integration_email:
    resource: "@KoalamonIntegrationEmailBundle/Resources/config/routing.yml"
    prefix:   /