services:

    koalamonintegration.webhook.init:
        class: KoalamonIntegrations\WebhookBundle\EventListener\IntegrationListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.integration.init', method: onInit }