services:

    koalamonintegration.webhook.init:
        class: KoalamonIntegration\WebhookBundle\EventListener\IntegrationListener
        arguments: [ "@service_container" ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.integration.init', method: onInit }