services:

    koalamonintegration.email.init:
        class: KoalamonIntegration\EmailBundle\EventListener\IntegrationListener
        arguments: [ "@service_container" ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.integration.init', method: onInit }